name: CI

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['**']

env:
  APP_ENV: testing
  CI: true
  AUTH0_DOMAIN: https://dev-lym12krcz8ycyqxr.us.auth0.com

jobs:
  setup-and-build:
    name: Install & Build Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0

      - name: Cache node_modules
        id: cache-node
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: npm ci

      - name: Build frontend
        run: npm run build

  codestyle:
    name: Lint & Prettier
    runs-on: ubuntu-latest
    needs: setup-and-build
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.11.0

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache-node.outputs.cache-hit != 'true'
        run:  npm ci

      - name: Run ESLint
        run: npm run lint:eslint

      - name: Run Prettier
        run: npm run lint:prettier
